// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"mysurl1/internal/middleware"
	"mysurl1/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authMiddleware := middleware.NewAuthMiddleware(serverCtx.Config.Auth)
	operationLogMiddleware := middleware.NewOperationLogMiddleware(serverCtx.UserOperationLogDAO)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:code",
				Handler: RedirectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: operationLogMiddleware.Handle(LoginHandler(serverCtx)),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
	server.AddRoutes(rest.WithMiddlewares(
		[]rest.Middleware{operationLogMiddleware.Handle, authMiddleware.Handle},
		rest.Route{
			Method:  http.MethodPost,
			Path:    "/api/v1/links",
			Handler: CreateLinkHandler(serverCtx),
		},
	))
	server.AddRoutes(rest.WithMiddlewares(
		[]rest.Middleware{authMiddleware.Handle},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/v1/links/mine",
			Handler: ListUserLinksHandler(serverCtx),
		},
	))
	server.AddRoutes(rest.WithMiddlewares(
		[]rest.Middleware{authMiddleware.Handle},
		rest.Route{
			Method:  http.MethodGet,
			Path:    "/api/v1/user-operation-logs",
			Handler: ListUserOperationLogsHandler(serverCtx),
		},
	))
}
