// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateLinkRequest struct {
	LongURL string `json:"long_url"`
}

type RegisterRequest struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthUser struct {
	ID       uint64 `json:"id"`
	Username string `json:"username"`
}

type AuthResponse struct {
	Token     string   `json:"token"`
	ExpiresAt int64    `json:"expires_at"`
	User      AuthUser `json:"user"`
}

type CreateLinkResponse struct {
	ShortCode   string `json:"short_code"`
	ShortURL    string `json:"short_url"`
	OriginalURL string `json:"original_url"`
}

type UserLinkItem struct {
	ID          uint64 `json:"id"`
	ShortCode   string `json:"short_code"`
	ShortURL    string `json:"short_url"`
	OriginalURL string `json:"original_url"`
	VisitCount  uint64 `json:"visit_count"`
	CreatedAt   int64  `json:"created_at"`
}

type ListUserLinksRequest struct {
	LastID      uint64 `form:"last_id,optional"`
	Limit       int    `form:"limit,optional"`
	ShortCode   string `form:"short_code,optional"`
	OriginalURL string `form:"original_url,optional"`
}

type UserLinkListResponse struct {
	Items      []UserLinkItem `json:"items"`
	Total      int64          `json:"total"`
	Limit      int            `json:"limit"`
	HasMore    bool           `json:"has_more"`
	NextLastID uint64         `json:"next_last_id"`
}

type ListUserOperationLogsRequest struct {
	LastID uint64 `form:"last_id,optional"`
	Limit  int    `form:"limit,optional"`
}

type UserOperationLogItem struct {
	ID         uint64 `json:"id"`
	Action     string `json:"action"`
	Result     string `json:"result"`
	TargetID   uint64 `json:"target_id,omitempty"`
	TargetCode string `json:"target_code,omitempty"`
	CreatedAt  int64  `json:"created_at"`
}

type UserOperationLogListResponse struct {
	Items      []UserOperationLogItem `json:"items"`
	Total      int64                  `json:"total"`
	Limit      int                    `json:"limit"`
	HasMore    bool                   `json:"has_more"`
	NextLastID uint64                 `json:"next_last_id"`
}

type RedirectRequest struct {
	Code string `path:"code"`
}
