// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateLinkRequest struct {
	LongURL string `json:"long_url"`
}

type BatchCreateLinksRequest struct {
	LongURLs []string `json:"long_urls"`
}

type RegisterRequest struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthUser struct {
	ID       uint64 `json:"id"`
	Username string `json:"username"`
}

type AuthResponse struct {
	Token     string   `json:"token"`
	ExpiresAt int64    `json:"expires_at"`
	User      AuthUser `json:"user"`
}

type CreateLinkResponse struct {
	ShortCode   string `json:"short_code"`
	ShortURL    string `json:"short_url"`
	OriginalURL string `json:"original_url"`
}

type BatchCreateLinkItem struct {
	Index       int    `json:"index"`
	LongURL     string `json:"long_url"`
	Success     bool   `json:"success"`
	ShortCode   string `json:"short_code,omitempty"`
	ShortURL    string `json:"short_url,omitempty"`
	OriginalURL string `json:"original_url,omitempty"`
	Error       string `json:"error,omitempty"`
}

type BatchCreateLinksResponse struct {
	Items        []BatchCreateLinkItem `json:"items"`
	Total        int                   `json:"total"`
	SuccessCount int                   `json:"success_count"`
	FailedCount  int                   `json:"failed_count"`
}

type UserLinkItem struct {
	ID          uint64 `json:"id"`
	ShortCode   string `json:"short_code"`
	ShortURL    string `json:"short_url"`
	OriginalURL string `json:"original_url"`
	VisitCount  uint64 `json:"visit_count"`
	CreatedAt   int64  `json:"created_at"`
}

type ListUserLinksRequest struct {
	LastID      uint64 `form:"last_id,optional"`
	Limit       int    `form:"limit,optional"`
	ShortCode   string `form:"short_code,optional"`
	OriginalURL string `form:"original_url,optional"`
}

type UserLinkListResponse struct {
	Items      []UserLinkItem `json:"items"`
	Total      int64          `json:"total"`
	Limit      int            `json:"limit"`
	HasMore    bool           `json:"has_more"`
	NextLastID uint64         `json:"next_last_id"`
}

type ListUserOperationLogsRequest struct {
	LastID uint64 `form:"last_id,optional"`
	Limit  int    `form:"limit,optional"`
	Action string `form:"action,optional"`
}

type UserOperationLogItem struct {
	ID        uint64 `json:"id"`
	Result    string `json:"result"`
	Reason    string `json:"reason,omitempty"`
	CreatedAt int64  `json:"created_at"`
}

type UserOperationLogListResponse struct {
	Items      []UserOperationLogItem `json:"items"`
	Total      int64                  `json:"total"`
	Limit      int                    `json:"limit"`
	HasMore    bool                   `json:"has_more"`
	NextLastID uint64                 `json:"next_last_id"`
}

type RedirectRequest struct {
	Code string `path:"code"`
}
